### ISSUE TITLE
Get NGINX configured and installed

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/os-base#3]
Get NGINX configured and installed with the image

**Comment by nolim1t** [comment]
Ideally we should get nginx installed

**Comment by nolim1t** [comment]
Reading material:

https://hub.docker.com/_/nginx

**Comment by nolim1t** [comment]
This is now added

**Comment by mayankchhabra** [comment]
Can we close this issue if NGINX is installed?

**Comment by nolim1t** [comment]
its not in master branch yet.

This will automatically be closed when I merge the PR.
